'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import {
  FiBook,
  FiLock,
  FiActivity,
  FiLayers,
  FiKey,
  FiShield,
  FiCheckCircle,
  FiArrowRight,
  FiDollarSign,
  FiCpu,
  FiHelpCircle,
  FiChevronDown,
  FiChevronUp,
} from 'react-icons/fi';
import {
  RiRobot2Line,
  RiShieldCheckLine,
  RiExchangeFundsLine,
  RiBankCardLine,
  RiRouteLine,
} from 'react-icons/ri';

export default function AppDocsPage() {
  const [activeTab, setActiveTab] = useState<'HOW_IT_WORKS' | 'CALCULATOR' | 'PRIVACY' | 'FAQ'>('HOW_IT_WORKS');
  const [calcAmount, setCalcAmount] = useState<number>(5000);
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const seniorEarn = (calcAmount * 0.085).toFixed(2);
  const mezzEarn = (calcAmount * 0.142).toFixed(2);
  const juniorEarn = (calcAmount * 0.228).toFixed(2);

  const faqs = [
    {
      q: 'What is Kudex and why should I use it?',
      a: 'Kudex is an institutional-grade decentralized platform for confidential settlements and high-yield real-world asset credit vaults. You can make private transfers with zero public balance leakage, earn up to 22.8% APY across structured credit tranches, and trade with instant solver execution with zero sandwich attacks.',
    },
    {
      q: 'How does client-side note confidentiality protect my privacy?',
      a: 'When you shield assets into Kudex, your balance is converted into a private cryptographic commitment note stored securely in your browser. Block explorers and external observers cannot link your deposits to your identity or track your recipient balances. You can also generate read-only auditor viewing keys for tax or corporate accounting.',
    },
    {
      q: 'How do Credit Vault tranches work and where does the yield come from?',
      a: 'Yield is generated by institutional borrowers collateralizing real-world asset portfolios. To protect depositors, credit vaults are divided into waterfalls: Senior tranches have first claim on all repayments and principal insurance; Junior tranches earn the highest return (22.8% APY) in exchange for first-loss risk absorption.',
    },
    {
      q: 'What is Default-as-a-Service (DaaS) risk protection?',
      a: 'Traditional DeFi liquidations trigger violent market sell-offs and liquidator bonuses that harm depositors. Kudex DaaS continuously monitors solvency health factors. If distress occurs, debt haircuts are amortized smoothly through the Junior reserve buffer, shielding Senior principal from liquidation cascades.',
    },
    {
      q: 'How does KUDEX AGENT execute trades without signature popups?',
      a: 'You can delegate temporary, bounded session policies to the autonomous Kudex Agent. You configure strict spending caps (e.g. up to $5,000), time limits, and allowed contract actions. The agent executes orders instantly in the background without prompting you with wallet confirmation modals on every click, and you can revoke the policy anytime in one click.',
    },
    {
      q: 'How do solvers fulfill RFQ orders without MEV or front-running?',
      a: 'Orders on Kudex are formulated as private off-chain intents. Certified institutional solvers compete to provide the best exchange rate. Transactions settle atomically in a single block once matched, meaning searchers and arbitrage bots in the public mempool cannot see or front-run your trade.',
    },
  ];

  return (
    <div className="space-y-8">
      {/* Workspace Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-slate-200 dark:border-[#21293D]">
        <div>
          <h2 className="text-2xl font-bold font-mono tracking-tight text-slate-900 dark:text-neutral-100">
            User Guide & Knowledge Center
          </h2>
          <p className="text-sm text-slate-600 dark:text-neutral-400 mt-1">
            Learn how to shield funds, earn institutional yields, automate execution with Kudex Agent, and protect your capital.
          </p>
        </div>

        <Link
          href="/docs"
          className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-[#161C2B] dark:hover:bg-[#21293D] text-slate-800 dark:text-neutral-200 border border-slate-200 dark:border-[#21293D] text-xs font-semibold font-mono transition"
        >
          <span>Public Specs</span>
          <FiArrowRight className="w-3.5 h-3.5 text-[#00E599]" />
        </Link>
      </div>

      {/* Navigation Tabs */}
      <div className="flex border-b border-slate-200 dark:border-[#21293D] gap-2 overflow-x-auto pb-1">
        {[
          { key: 'HOW_IT_WORKS', label: 'How Kudex Works', icon: FiBook },
          { key: 'CALCULATOR', label: 'Yield Simulator', icon: FiDollarSign },
          { key: 'PRIVACY', label: 'Privacy & Security', icon: FiLock },
          { key: 'FAQ', label: 'Frequently Asked Questions', icon: FiHelpCircle },
        ].map((tab) => {
          const Icon = tab.icon;
          return (
            <button
              key={tab.key}
              onClick={() => setActiveTab(tab.key as any)}
              className={`flex items-center gap-2 px-5 py-3 rounded-t-xl text-sm font-medium transition border-b-2 font-mono whitespace-nowrap ${
                activeTab === tab.key
                  ? 'border-[#00E599] text-[#00E599] bg-white dark:bg-[#0E121B]'
                  : 'border-transparent text-slate-500 dark:text-neutral-400 hover:text-slate-800 dark:hover:text-neutral-200'
              }`}
            >
              <Icon className="w-4 h-4" />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* Tab 1: How It Works */}
      {activeTab === 'HOW_IT_WORKS' && (
        <div className="space-y-8">
          {/* 3 Simple Steps */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="p-6 rounded-2xl border border-slate-200 dark:border-[#21293D] bg-white dark:bg-[#0E121B] space-y-4 shadow-sm transition-colors duration-200">
              <div className="w-10 h-10 rounded-xl bg-[#00E599]/10 text-[#00E599] flex items-center justify-center font-bold font-mono text-base border border-[#00E599]/20">
                1
              </div>
              <h3 className="text-base font-bold font-mono text-slate-900 dark:text-neutral-100">
                Deposit or Bridge Assets
              </h3>
              <p className="text-sm text-slate-600 dark:text-neutral-400 leading-relaxed">
                Connect your wallet and fund your account with pUSD or bridge liquidity instantly from Ethereum, Base, or Arbitrum with fast solver relay.
              </p>
              <div className="pt-2">
                <Link
                  href="/app/bridge"
                  className="inline-flex items-center gap-1.5 text-xs font-mono font-bold text-[#00E599] hover:underline"
                >
                  <span>Open Bridge Gateway</span>
                  <FiArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>

            <div className="p-6 rounded-2xl border border-slate-200 dark:border-[#21293D] bg-white dark:bg-[#0E121B] space-y-4 shadow-sm transition-colors duration-200">
              <div className="w-10 h-10 rounded-xl bg-[#2E68FF]/10 text-[#2E68FF] flex items-center justify-center font-bold font-mono text-base border border-[#2E68FF]/20">
                2
              </div>
              <h3 className="text-base font-bold font-mono text-slate-900 dark:text-neutral-100">
                Shield Funds or Earn Yield
              </h3>
              <p className="text-sm text-slate-600 dark:text-neutral-400 leading-relaxed">
                Choose between confidential private transfers with client-side encrypted notes, or deposit into institutional credit vaults to earn up to 22.8% APY.
              </p>
              <div className="pt-2">
                <Link
                  href="/app/vaults"
                  className="inline-flex items-center gap-1.5 text-xs font-mono font-bold text-[#2E68FF] hover:underline"
                >
                  <span>Explore Credit Tranches</span>
                  <FiArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>

            <div className="p-6 rounded-2xl border border-slate-200 dark:border-[#21293D] bg-white dark:bg-[#0E121B] space-y-4 shadow-sm transition-colors duration-200">
              <div className="w-10 h-10 rounded-xl bg-[#00E599]/10 text-[#00E599] flex items-center justify-center font-bold font-mono text-base border border-[#00E599]/20">
                3
              </div>
              <h3 className="text-base font-bold font-mono text-slate-900 dark:text-neutral-100">
                Automate with Kudex Agent
              </h3>
              <p className="text-sm text-slate-600 dark:text-neutral-400 leading-relaxed">
                Chat naturally with KUDEX AGENT to find the best swap prices, verify solvency health, and execute trades without disruptive wallet popups.
              </p>
              <div className="pt-2">
                <Link
                  href="/app/overview"
                  className="inline-flex items-center gap-1.5 text-xs font-mono font-bold text-[#00E599] hover:underline"
                >
                  <span>Launch Agent Terminal</span>
                  <FiArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>
          </div>

          {/* Feature Matrix */}
          <div className="p-6 sm:p-8 rounded-2xl border border-slate-200 dark:border-[#21293D] bg-white dark:bg-[#0E121B] space-y-6 shadow-sm transition-colors duration-200">
            <h3 className="text-lg font-bold font-mono text-slate-900 dark:text-neutral-100">
              Protocol Capability Matrix
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
              <div className="p-4 rounded-xl bg-slate-50 dark:bg-[#161C2B] border border-slate-200 dark:border-[#21293D] space-y-2">
                <div className="flex items-center gap-2 text-[#00E599]">
                  <RiBankCardLine className="w-4 h-4" />
                  <span className="font-bold text-xs font-mono uppercase">Private Transfers</span>
                </div>
                <p className="text-xs text-slate-600 dark:text-neutral-400 leading-relaxed">
                  Mint encrypted notes, disburse contractor payroll, and send payments without public trail.
                </p>
              </div>

              <div className="p-4 rounded-xl bg-slate-50 dark:bg-[#161C2B] border border-slate-200 dark:border-[#21293D] space-y-2">
                <div className="flex items-center gap-2 text-[#2E68FF]">
                  <RiExchangeFundsLine className="w-4 h-4" />
                  <span className="font-bold text-xs font-mono uppercase">Zero-MEV RFQ</span>
                </div>
                <p className="text-xs text-slate-600 dark:text-neutral-400 leading-relaxed">
                  Off-chain solver quote competition settles atomically in one block. Immunized against sandwich bots.
                </p>
              </div>

              <div className="p-4 rounded-xl bg-slate-50 dark:bg-[#161C2B] border border-slate-200 dark:border-[#21293D] space-y-2">
                <div className="flex items-center gap-2 text-[#00E599]">
                  <FiLayers className="w-4 h-4" />
                  <span className="font-bold text-xs font-mono uppercase">Credit Tranches</span>
                </div>
                <p className="text-xs text-slate-600 dark:text-neutral-400 leading-relaxed">
                  Choose your risk tolerance: Senior (8.5% safe), Mezzanine (14.2%), or Junior (22.8% max yield).
                </p>
              </div>

              <div className="p-4 rounded-xl bg-slate-50 dark:bg-[#161C2B] border border-slate-200 dark:border-[#21293D] space-y-2">
                <div className="flex items-center gap-2 text-amber-500">
                  <FiActivity className="w-4 h-4" />
                  <span className="font-bold text-xs font-mono uppercase">DaaS Solvency</span>
                </div>
                <p className="text-xs text-slate-600 dark:text-neutral-400 leading-relaxed">
                  Automated debt restructuring prevents flash liquidations and stabilizes health factors above 1.15x.
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Tab 2: Interactive Yield Simulator */}
      {activeTab === 'CALCULATOR' && (
        <div className="space-y-6">
          <div className="p-6 sm:p-8 rounded-2xl border border-slate-200 dark:border-[#21293D] bg-white dark:bg-[#0E121B] space-y-6 shadow-sm transition-colors duration-200">
            <div>
              <h3 className="text-lg font-bold font-mono text-slate-900 dark:text-neutral-100">
                Interactive Tranche Earnings Simulator
              </h3>
              <p className="text-sm text-slate-600 dark:text-neutral-400 mt-1">
                Calculate your projected annual return across Kudex credit facilities based on your deposit amount.
              </p>
            </div>

            {/* Slider & Presets */}
            <div className="space-y-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <label className="text-xs font-mono uppercase text-slate-500 dark:text-neutral-400">
                  Simulated Deposit Amount (pUSD)
                </label>
                <div className="text-2xl font-extrabold font-mono text-slate-900 dark:text-neutral-100 tabular-nums">
                  ${calcAmount.toLocaleString()} pUSD
                </div>
              </div>

              <input
                type="range"
                min="500"
                max="50000"
                step="500"
                value={calcAmount}
                onChange={(e) => setCalcAmount(Number(e.target.value))}
                className="w-full accent-[#00E599] bg-slate-200 dark:bg-[#161C2B] rounded-lg cursor-pointer h-2"
              />

              <div className="flex gap-2">
                {[1000, 5000, 10000, 25000].map((amt) => (
                  <button
                    key={amt}
                    onClick={() => setCalcAmount(amt)}
                    className={`px-3 py-1 rounded-lg text-xs font-mono font-medium transition border ${
                      calcAmount === amt
                        ? 'bg-[#00E599] text-[#06080D] font-bold border-[#00E599]'
                        : 'bg-slate-100 dark:bg-[#161C2B] text-slate-700 dark:text-neutral-300 border-slate-200 dark:border-[#21293D] hover:border-slate-400'
                    }`}
                  >
                    ${amt.toLocaleString()}
                  </button>
                ))}
              </div>
            </div>

            {/* Tranche Comparison Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-4">
              {/* Senior */}
              <div className="p-6 rounded-2xl border border-slate-200 dark:border-[#21293D] bg-slate-50 dark:bg-[#161C2B] space-y-4 transition-colors duration-200">
                <div className="flex items-center justify-between">
                  <span className="px-2.5 py-0.5 rounded text-xs font-mono font-bold bg-[#00E599]/10 text-[#00E599]">
                    Grade AAA
                  </span>
                  <span className="text-xs font-mono text-slate-500 dark:text-neutral-400">Principal Shield</span>
                </div>
                <div>
                  <h4 className="text-base font-bold font-mono text-slate-900 dark:text-neutral-100">
                    Senior Tranche
                  </h4>
                  <div className="text-2xl font-extrabold font-mono text-[#00E599] tabular-nums mt-1">
                    8.50% APY
                  </div>
                </div>
                <div className="p-3 rounded-xl bg-white dark:bg-[#0E121B] border border-slate-200 dark:border-[#21293D] space-y-1 text-xs font-mono">
                  <span className="text-slate-500 dark:text-neutral-400">Projected 1-Year Return:</span>
                  <div className="text-base font-bold text-slate-900 dark:text-neutral-100 tabular-nums">
                    +${seniorEarn} pUSD
                  </div>
                </div>
                <p className="text-xs text-slate-600 dark:text-neutral-400">
                  Ideal for conservative corporate treasuries. Junior tranches absorb losses first.
                </p>
                <Link
                  href="/app/vaults"
                  className="w-full inline-flex items-center justify-center gap-1.5 py-2.5 rounded-xl bg-[#00E599] text-[#06080D] font-bold text-xs transition"
                >
                  <span>Deposit Senior</span>
                  <FiArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>

              {/* Mezzanine */}
              <div className="p-6 rounded-2xl border border-slate-200 dark:border-[#21293D] bg-slate-50 dark:bg-[#161C2B] space-y-4 transition-colors duration-200">
                <div className="flex items-center justify-between">
                  <span className="px-2.5 py-0.5 rounded text-xs font-mono font-bold bg-[#2E68FF]/10 text-[#2E68FF]">
                    Grade BBB
                  </span>
                  <span className="text-xs font-mono text-slate-500 dark:text-neutral-400">Balanced Risk</span>
                </div>
                <div>
                  <h4 className="text-base font-bold font-mono text-slate-900 dark:text-neutral-100">
                    Mezzanine Tranche
                  </h4>
                  <div className="text-2xl font-extrabold font-mono text-[#2E68FF] tabular-nums mt-1">
                    14.20% APY
                  </div>
                </div>
                <div className="p-3 rounded-xl bg-white dark:bg-[#0E121B] border border-slate-200 dark:border-[#21293D] space-y-1 text-xs font-mono">
                  <span className="text-slate-500 dark:text-neutral-400">Projected 1-Year Return:</span>
                  <div className="text-base font-bold text-slate-900 dark:text-neutral-100 tabular-nums">
                    +${mezzEarn} pUSD
                  </div>
                </div>
                <p className="text-xs text-slate-600 dark:text-neutral-400">
                  Enhanced yield with intermediate credit buffering and secondary shortfall coverage.
                </p>
                <Link
                  href="/app/vaults"
                  className="w-full inline-flex items-center justify-center gap-1.5 py-2.5 rounded-xl bg-[#2E68FF] text-white font-bold text-xs transition"
                >
                  <span>Deposit Mezzanine</span>
                  <FiArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>

              {/* Junior */}
              <div className="p-6 rounded-2xl border border-slate-200 dark:border-[#21293D] bg-slate-50 dark:bg-[#161C2B] space-y-4 transition-colors duration-200">
                <div className="flex items-center justify-between">
                  <span className="px-2.5 py-0.5 rounded text-xs font-mono font-bold bg-amber-500/10 text-amber-500 dark:text-amber-400">
                    Grade BB
                  </span>
                  <span className="text-xs font-mono text-slate-500 dark:text-neutral-400">High Yield</span>
                </div>
                <div>
                  <h4 className="text-base font-bold font-mono text-slate-900 dark:text-neutral-100">
                    Junior Tranche
                  </h4>
                  <div className="text-2xl font-extrabold font-mono text-amber-500 dark:text-amber-400 tabular-nums mt-1">
                    22.80% APY
                  </div>
                </div>
                <div className="p-3 rounded-xl bg-white dark:bg-[#0E121B] border border-slate-200 dark:border-[#21293D] space-y-1 text-xs font-mono">
                  <span className="text-slate-500 dark:text-neutral-400">Projected 1-Year Return:</span>
                  <div className="text-base font-bold text-slate-900 dark:text-neutral-100 tabular-nums">
                    +${juniorEarn} pUSD
                  </div>
                </div>
                <p className="text-xs text-slate-600 dark:text-neutral-400">
                  Maximizes return for risk-seeking capital by serving as the protocol first-loss buffer.
                </p>
                <Link
                  href="/app/vaults"
                  className="w-full inline-flex items-center justify-center gap-1.5 py-2.5 rounded-xl bg-amber-500 text-[#06080D] font-bold text-xs transition"
                >
                  <span>Deposit Junior</span>
                  <FiArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Tab 3: Privacy & Security */}
      {activeTab === 'PRIVACY' && (
        <div className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="p-6 sm:p-8 rounded-2xl border border-slate-200 dark:border-[#21293D] bg-white dark:bg-[#0E121B] space-y-4 shadow-sm transition-colors duration-200">
              <div className="p-3 rounded-xl bg-[#00E599]/10 text-[#00E599] w-fit border border-[#00E599]/20">
                <FiLock className="w-6 h-6" />
              </div>
              <h3 className="text-base font-bold font-mono text-slate-900 dark:text-neutral-100">
                How Your Transactions Stay Private
              </h3>
              <p className="text-sm text-slate-600 dark:text-neutral-400 leading-relaxed">
                When you execute transfers on regular blockchains, your wallet address and balance are publicly visible to anyone who queries the block explorer.
              </p>
              <p className="text-sm text-slate-600 dark:text-neutral-400 leading-relaxed">
                Kudex transforms your token balances into encrypted commitment notes. The ledger only records hashed proofs, making it impossible for bots or third parties to view payment amounts or track counterparties.
              </p>
              <div className="pt-2">
                <Link
                  href="/app/settlement"
                  className="inline-flex items-center gap-1.5 text-xs font-mono font-bold text-[#00E599] hover:underline"
                >
                  <span>Shield Tokens Now</span>
                  <FiArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>

            <div className="p-6 sm:p-8 rounded-2xl border border-slate-200 dark:border-[#21293D] bg-white dark:bg-[#0E121B] space-y-4 shadow-sm transition-colors duration-200">
              <div className="p-3 rounded-xl bg-[#2E68FF]/10 text-[#2E68FF] w-fit border border-[#2E68FF]/20">
                <RiShieldCheckLine className="w-6 h-6" />
              </div>
              <h3 className="text-base font-bold font-mono text-slate-900 dark:text-neutral-100">
                Auditor Compliance Without Compromise
              </h3>
              <p className="text-sm text-slate-600 dark:text-neutral-400 leading-relaxed">
                Corporate treasuries and regulated funds need privacy from competitors, but must remain compliant with auditors, tax authorities, and legal counsel.
              </p>
              <p className="text-sm text-slate-600 dark:text-neutral-400 leading-relaxed">
                Kudex enables you to generate asymmetric viewing keys with customizable expiration dates. Certified auditors can inspect your inbound and outbound transaction proofs without exposing your activity to the general public.
              </p>
              <div className="pt-2">
                <Link
                  href="/app/compliance"
                  className="inline-flex items-center gap-1.5 text-xs font-mono font-bold text-[#2E68FF] hover:underline"
                >
                  <span>Generate Auditor Viewing Key</span>
                  <FiArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Tab 4: Interactive FAQ */}
      {activeTab === 'FAQ' && (
        <div className="space-y-4">
          {faqs.map((faq, index) => {
            const isOpen = openFaq === index;
            return (
              <div
                key={index}
                className="rounded-2xl border border-slate-200 dark:border-[#21293D] bg-white dark:bg-[#0E121B] overflow-hidden shadow-sm transition-colors duration-200"
              >
                <button
                  onClick={() => setOpenFaq(isOpen ? null : index)}
                  className="w-full p-5 text-left flex items-center justify-between gap-4 font-mono font-bold text-sm text-slate-900 dark:text-neutral-100 hover:bg-slate-50 dark:hover:bg-[#161C2B]/50 transition"
                >
                  <span>{faq.q}</span>
                  {isOpen ? (
                    <FiChevronUp className="w-4 h-4 text-[#00E599] flex-shrink-0" />
                  ) : (
                    <FiChevronDown className="w-4 h-4 text-slate-400 flex-shrink-0" />
                  )}
                </button>
                {isOpen && (
                  <div className="px-5 pb-5 text-sm text-slate-600 dark:text-neutral-400 font-sans leading-relaxed border-t border-slate-100 dark:border-[#21293D] pt-3">
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
